import Head from 'next/head'

export default function PageHead() {
    return (
        <Head>
            <title>SUNDAY MOURNERS</title>
            <meta name="Sunday Mourners Website" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Codystar&display=swap" rel="stylesheet" />
            <link href="https://fonts.googleapis.com/css2?family=Alan+Sans:wght@300..900&family=Montserrat:ital,wght@0,100..900;1,100..900&family=Unbounded:wght@200..900&display=swap" rel="stylesheet"/>
            <script src="https://kit.fontawesome.com/b52fd21c14.js" crossOrigin="anonymous"></script>
            <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet" />
        </Head>
    )
}
