import Head from 'next/head'

export default function PageHead() {
    return (
        <Head>
            <title>SUNDAY MOURNERS</title>
            <meta name="Sunday Mourners Website" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />

        </Head>
    )
}
