import Head from 'next/head'
import { motion } from 'framer-motion';
import styled, { keyframes } from 'styled-components'
import useSWR,{SWRConfig} from 'swr'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {} from "@fortawesome/free-solid-svg-icons";
import React from 'react';
import { render } from "react-dom";

// get our fontawesome imports
import { faHome } from "@fortawesome/free-solid-svg-icons";



import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
  Images,
  Marquee
} from '../components/sharedstyles'
import { useState } from 'react';



const fetcher = (url) => fetch(url).then((res) => res.json())

const ReadMoreSection = () => {
  const [showReadMore, setShowReadMore] = useState(false);

  const toggleReadMore = () => {
    setShowReadMore(!showReadMore);
  };

  return (
    <ReadMore>

  
    <div>
      <h2 className="toggle" onClick={toggleReadMore}>{showReadMore ? 'Hide' : 'Read More'}</h2>
      {showReadMore && (
        <div className="more">
          <p className='quote'><span>“Southern California rock and roll only with a slightly harder-edged east coast approach. Combining the embryonic stage of Parquet Courts with the Velvet Underground and Bowie”</span> - <span className='attribution'>Glide Magazine</span></p>
          <p>Sunday Mourners started humbly as The Good Job Botanical Band in the university dorm rooms of lead guitarist Max Pugh and lead localist Quinn Robinson. It was not until after they were joined by drummer Z Evan Long and bassist Casey Hoerman that the band bloomed into the Sunday Mourners. A protopunk-inspired noisy onslaught of raw rock and roll energy mixed with the intricacies of 60's/70s freak-folk and country music. Characterized by their energetic live performances, DIY production, and eclectic music taste, Sunday Mourners excite listeners with glimpses into a past that never was.</p>
        </div>
      )}
    </div>
      </ReadMore>
  );
};
  

export default function Home() {
  const { data: events, error } = useSWR('/api', fetcher);
  



  // console.log(events)
  return (
    
    <Container>
      <Head>
        <title>SUNDAY MOURNERS</title>
        <meta name="Sunday Mourners Website" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link href="https://fonts.googleapis.com/css2?family=Codystar&display=swap" rel="stylesheet"/>
        <script src="https://kit.fontawesome.com/b52fd21c14.js" crossOrigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet"/>


      </Head>
      <Main>
        <Images>
          <img src="/images/splash.jpeg" alt="Max and quinn" />
          <img src="/images/wh.JPG" alt="Max and quinn" />
          <img src="/images/mq2.JPG" alt="Max and quinn" />
          <img src="/images/mq.JPG" alt="Max and quinn" />
        </Images>
        <TopMarquee direction="right"><h1 className='glow'>Sunday Mourners</h1></TopMarquee>
        <BottomMarquee direction="left" className=""><h1 className='glow'>Sunday Mourners</h1></BottomMarquee>
        <InfoContainer>
                <div className="listen">
                    <h2>Listen</h2>
                    <iframe id="spotify" src="https://open.spotify.com/embed/artist/7zlE048Rl8GTsbWAP1MZeQ?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
                </div>
                <div className="contact">
                    <h2>Contact</h2>
                    <ul className="socials">
                        <li><a title="instagram "href="https://www.instagram.com/sundaymourners/">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"> <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg>
                        </a></li> 
                        <li><a title="spotify" href="https://open.spotify.com/artist/7zlE048Rl8GTsbWAP1MZeQ">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512"><path d="M248 8C111.1 8 0 119.1 0 256s111.1 248 248 248 248-111.1 248-248S384.9 8 248 8zm100.7 364.9c-4.2 0-6.8-1.3-10.7-3.6-62.4-37.6-135-39.2-206.7-24.5-3.9 1-9 2.6-11.9 2.6-9.7 0-15.8-7.7-15.8-15.8 0-10.3 6.1-15.2 13.6-16.8 81.9-18.1 165.6-16.5 237 26.2 6.1 3.9 9.7 7.4 9.7 16.5s-7.1 15.4-15.2 15.4zm26.9-65.6c-5.2 0-8.7-2.3-12.3-4.2-62.5-37-155.7-51.9-238.6-29.4-4.8 1.3-7.4 2.6-11.9 2.6-10.7 0-19.4-8.7-19.4-19.4s5.2-17.8 15.5-20.7c27.8-7.8 56.2-13.6 97.8-13.6 64.9 0 127.6 16.1 177 45.5 8.1 4.8 11.3 11 11.3 19.7-.1 10.8-8.5 19.5-19.4 19.5zm31-76.2c-5.2 0-8.4-1.3-12.9-3.9-71.2-42.5-198.5-52.7-280.9-29.7-3.6 1-8.1 2.6-12.9 2.6-13.2 0-23.3-10.3-23.3-23.6 0-13.6 8.4-21.3 17.4-23.9 35.2-10.3 74.6-15.2 117.5-15.2 73 0 149.5 15.2 205.4 47.8 7.8 4.5 12.9 10.7 12.9 22.6 0 13.6-11 23.3-23.2 23.3z"/></svg>
                        </a></li>
                        <li><a title="linktree" href="https://linktr.ee/sundaymourners">
                        <svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd" clip-rule="evenodd" viewBox="0 0 417 512.238"><path  fill-rule="nonzero" d="M171.274 344.942h74.09v167.296h-74.09V344.942zM0 173.468h126.068l-89.622-85.44 49.591-50.985 85.439 87.829V0h74.086v124.872L331 37.243l49.552 50.785-89.58 85.24H417v70.502H290.252l90.183 87.629L331 381.192 208.519 258.11 86.037 381.192l-49.591-49.591 90.218-87.631H0v-70.502z"/></svg>
                        </a></li>
                    </ul>
                  
                    <a id='book' href = "mailto:sundaymourner@gmail.com?subject = Booking?Message=">
                        Booking
                    </a>
                </div>
            </InfoContainer>
            <Events>
            <ReadMoreSection />
              <h2>Events</h2>
              <div>
                {Array.isArray(events) ? (
                  <div className='eventList'>
                    {events
                      .sort((a, b) => new Date(b.datetime).getTime() - new Date(a.datetime).getTime()) // Sort events by date
                      .map((event) => (
                        <div key={event.id}>
                          <div >
                            <a className='event' href={event.url}>
                              {event.venue.name} - {event.datetime.split('T')[0]}
                            </a>
                          </div>
                        </div>
                      ))}
                  </div>
                ) : (
                  <p>Loading events...</p>
                )}
              </div>
            </Events>
      
      </Main>
    </Container>
  )
}






const glowAnimation = keyframes`
  from {
    text-shadow: 0 0 10px #fff, 0 0 10px #fff, 0 0 10px #f6fc59, 0 0 10px #f6fc59, 0 0 13px #f6fc59, 0 0 20px #f6fc59, 0 0 10px #f6fc59;
  }
  
  to {
    text-shadow: 0 0 5px #fff, 0 0 5px #f6fc59, 0 0 0px #f6fc59, 0 0 10px #f6fc59, 0 0 10px #f6fc59, 0 0 10px #f6fc59, 0 0 10px #f6fc59;
  }
`;


const TopMarquee=styled(Marquee)`
  
  top:0;
 
`
const BottomMarquee=styled(Marquee)`
  bottom:0;

`
const InfoContainer = styled.div`
  margin:0;
  h2{
      margin-block-start:.25em;
      margin-block-end:.25em;
  }

  display: flex;
  padding-inline: 55px;

  justify-content: space-between;
  width: 100%;
  @media screen and (max-width: 720px) {
    flex-direction: column;
    padding-bottom: 10px;
    padding-inline: 0px;
    align-items: center;
    justify-content: center;
  }
  
  .contact{

    #book{
      background-color:white;
      color: black;
    }
    display: flex;
    flex-direction: column;
    align-items:flex-end;
    justify-content: start;
    flex:1;
    font-size: 3vw;
    z-index: 2;

    ul{
      svg{
        width: 5vw;
      }
      svg:hover{
        transition:.3s ease-in-out;
        transform: scale(1.1);
        fill: #f6fc59;
      }
      display: inline;
    }

    @media screen and (max-width: 720px) {
      display: flex;
        flex-direction: column;
        align-items:center;
        justify-items: center;
        flex:1;
        ul.socials{
        /* make svg's be white */
            align-self: center;
            justify-self: center;
            margin:0;
            padding:0;
            padding-top: 10px;
            padding-bottom: 10px;
          }
    }
      
}
.listen{
    display: flex;
    flex-direction: column;
    width: 80%;
    flex:1;
    font-size: 3vw;
    z-index: 2;
    
}
li{
    display:inline;
}
li a{
  margin:10px;
  padding:0;
  color: white;
  background:none;
  font-size: 3;

}
i:hover{
    /* color: #f6fc59; */
    transition:.2s ease-in-out;
    transform: scale(1.1);
    transform: font-size(2rem); 
}




`

const Events = styled.div`
  display: flex;
  flex-direction: column;
  align-items:center;
  justify-content: center;
  z-index: 2;
  
  
  a{
    font-size: 3vw;
    color: white;
    background:none;
    @media screen and (max-width: 1020px) {
    font-size: 25px;
  }
  }
  a:hover{
    color: #f6fc59;
    transition:.2s ease-in-out;
  }
  .event:hover{
    transition:.2s ease-in-out;

    transform: scale(1.1);

  }
  .event{
    display: flex;
    text-align: center;
  }
  
  h2{
    font-size: 3vw;
    @media screen and (max-width: 720px) {
    font-size: 10vw;
  }
  }
  .eventList{
    display: flex;
    flex-direction: column;
    align-items:center;
    gap:50px;
    @media screen and (max-width: 720px) {
      font-size: 10vw;
    }
  }
  
  margin-bottom: 100px;
`

const ReadMore = styled.div`
  display: flex;
  flex-direction: column;
  align-items:center;
  padding:40px;
  justify-content: center;
  .toggle{
    width:fit-content
  }
  @media screen and (max-width: 720px) {
    margin: 0px;
    padding: 50px
  }
  .toggle:hover{
    cursor: pointer;
    color: #f6fc59; 
  }
  .quote{
    font-style: italic;
    color: #f6fc59;
    text-align: center;

  }
  p{
    font-size: 1.8vw;
    @media screen and (max-width: 850px) {
    font-size: 4vw;
  }
  }
  
  `